# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.30.0/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.30.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/uenoarisa/Desktop/lab/s1lidar_project_a/python_bindings

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/uenoarisa/Desktop/lab/s1lidar_project_a/python_bindings/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.30.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.30.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/uenoarisa/Desktop/lab/s1lidar_project_a/python_bindings/build/CMakeFiles /Users/uenoarisa/Desktop/lab/s1lidar_project_a/python_bindings/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/uenoarisa/Desktop/lab/s1lidar_project_a/python_bindings/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ultra_simple_wrapper

# Build rule for target.
ultra_simple_wrapper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ultra_simple_wrapper
.PHONY : ultra_simple_wrapper

# fast build rule for target.
ultra_simple_wrapper/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ultra_simple_wrapper.dir/build.make CMakeFiles/ultra_simple_wrapper.dir/build
.PHONY : ultra_simple_wrapper/fast

ultra_simple_wrapper.o: ultra_simple_wrapper.cpp.o
.PHONY : ultra_simple_wrapper.o

# target to build an object file
ultra_simple_wrapper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ultra_simple_wrapper.dir/build.make CMakeFiles/ultra_simple_wrapper.dir/ultra_simple_wrapper.cpp.o
.PHONY : ultra_simple_wrapper.cpp.o

ultra_simple_wrapper.i: ultra_simple_wrapper.cpp.i
.PHONY : ultra_simple_wrapper.i

# target to preprocess a source file
ultra_simple_wrapper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ultra_simple_wrapper.dir/build.make CMakeFiles/ultra_simple_wrapper.dir/ultra_simple_wrapper.cpp.i
.PHONY : ultra_simple_wrapper.cpp.i

ultra_simple_wrapper.s: ultra_simple_wrapper.cpp.s
.PHONY : ultra_simple_wrapper.s

# target to generate assembly for a file
ultra_simple_wrapper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ultra_simple_wrapper.dir/build.make CMakeFiles/ultra_simple_wrapper.dir/ultra_simple_wrapper.cpp.s
.PHONY : ultra_simple_wrapper.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ultra_simple_wrapper"
	@echo "... ultra_simple_wrapper.o"
	@echo "... ultra_simple_wrapper.i"
	@echo "... ultra_simple_wrapper.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

